# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09fcb16c83434fdde1fe98d78bf6a0b18434994d79ebdda5bb8eb7f1ed6da1dffe1dfa31c2dad5b8a0eb4d90ed2f7107e0386d28ad4721929a684f4e7c3c73d5

test:
  secret_key_base: dbbad388d8d150644b64eef86cbeefc2613b4905ab1fd1f7cc42276f9d3459bbe5e36e735aafac6b91d20cc36a28ef9cd0c760289c109a0b3633a82675495632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
